# Generated by Django 4.2.7 on 2023-11-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_side', '0003_product_shops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shops',
            field=models.ManyToManyField(to='shop_side.shop'),
        ),
    ]
